on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Exit if not on master branch
      #   if: endsWith(github.ref, 'master') == false
        if: github.ref == 'refs/heads/master'
        run: exit -1
      
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
        id: myBuildStep
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
      - run: echo 'Project Version: ${{ steps.myBuildStep.outputs.buildVersion }}'
